int N, cash, rest, note;
N = int.Parse(Console.ReadLine());
Console.WriteLine(N);
rest = N;
note = 100;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 100,00");
rest = rest % note;
note = 50;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 50,00");
rest = rest % note;
note = 20;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 20,00");
rest = rest % note;
note = 10;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 10,00");
rest = rest % note;
note = 5;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 5,00");
rest = rest % note;
note = 2;
cash = rest / note;
Console.WriteLine(cash + " nota(s) de R$ 2,00");
rest = rest % note;
Console.WriteLine(rest + " nota(s) de R$ 1,00");